### ISSUE TITLE
[Feature Request] Resize images in glossary

### ISSUE THREAD

**Issue by BigBoyBarney** [ripose-jp/Memento#268]
Hi!

I ran into a pretty funny issue while trying out the Jitendex dictionary.

![Image](https://github.com/user-attachments/assets/2c940904-9347-4578-9e10-b4f630555878)

![Image](https://github.com/user-attachments/assets/9746ea5e-20e0-4cf4-84e7-0ec137862ff7)

It seems to be using images (?) for the tags.
```html
<span style="vertical-align: text-bottom;margin-right: 0px;" data-code="v5s">
<img src="4b298f0076b35828e18b0a5620bff458.svg" title="Godan verb with 'su' ending" style="width: 2.97em;height: 1.2em;vertical-align: bottom;"></span>
<span style="vertical-align: text-bottom;margin-right: 0px;" data-code="vt">
<img src="e5c279dfff7b0701c9a117a60123291d.svg" title="transitive verb" style="width: 4.88em;height: 1.2em;vertical-align: bottom;"></span>
```

Would it be possible to use the `width` and `height` parameters to render them, so that they aren't comically large? :D

Thanks in advance! 

-----

This applies to everything that uses svgs:

https://github.com/user-attachments/assets/b82eb830-8133-4a50-aeb7-60ab351d9d11

**Comment by ripose-jp** [comment]
The Jitendex bug was reported in #223 and was solved by updating the dictionary to the latest. Yours is pretty old, so that's probably the cause.

Can you link me to that J-J dictionary that you're using so I can test it out?

**Comment by BigBoyBarney** [comment]
Thanks!

I was using the version from https://drive.google.com/drive/folders/1RXSkwOLLcSEIptGpoiDY2eaYAa-Ohu6x

Updating Jitendex solves the Jitendex related issue, since the markers are formatted as text.

However, the issue is still present in other dictionaries that use `svg`s like 三省堂国語辞典　第八版.

Example:

https://github.com/user-attachments/assets/fcca769b-1114-46af-a423-ff3f8792e774

**Comment by ripose-jp** [comment]
I found a copy of 三省堂国語辞典　第八版 and it seems like it might be limited by what Qt's rich text CSS implementation supports. I'll look into it further before coming to a conclusion.

**Comment by BigBoyBarney** [comment]
Thank you!

If it can't be done, maybe stripping the `svg`s from the widget might be a good alternative, if that's possible.

**Comment by ripose-jp** [comment]
I've mitigated the issue somewhat. Let me know if you find anything that this change breaks.

**Comment by BigBoyBarney** [comment]
![Image](https://github.com/user-attachments/assets/1e818bed-cb9c-41a5-9b07-00ce3dfd4de2)

That looks excellent, thank you very much! I'll let you know if I find anything else!
